package com.longofo.example.EchoApp;


/**
* EchoApp/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* Friday, June 29, 2018 4:29:11 PM EAT
*/

public interface EchoOperations 
{
  String echoString();
} // interface EchoOperations
